# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-01-08 01:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2018, 1, 8, 1, 55, 53, 635662, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
